/*     ___    ____  __    ___   _________
 *    /   |  / _  |/ /   / / | / /__  __/          Source Code Static Analyzer
 *   / /| | / / / / /   / /  |/ /  / /                  AdLint - Advanced Lint
 *  / __  |/ /_/ / /___/ / /|  /  / /
 * /_/  |_|_____/_____/_/_/ |_/  /_/  Copyright (C) 2010-2014, OGIS-RI Co.,Ltd.
 *
 * Project specific initial header file generated by adlintize 3.2.14
 * at 2015-10-23 20:09:45 +0900.
 */

/* Put project specific predefined macros and types here. */
#define BOARD_CUSTOM
#define SWI_DISABLE0
#define SOFTDEVICE_PRESENT
#define NRF51
#define S110
#define BLE_STACK_SUPPORT_REQD
